import React from "react";

const page = () => {
  return <div>
    <h1 className="text-4xl font-bold mb-6 ml-3">Terms of Service</h1>
<p className="text-lg mb-6 ml-3">By using our resume builder service, you agree to the following terms and conditions:<br></br>
  The content generated by our service, including but not limited to resumes, cover letters, and any other related materials
  may be generated or modified using artificial intelligence algorithms. While we strive for accuracy and quality, we cannot guarantee
  the completeness, accuracy, reliability, suitability, or availability of the generated content. Users are solely responsible
  for reviewing and verifying the accuracy and appropriateness of the generated content before use. We shall not be liable for any
  direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of profits,
  goodwill, use, data, or other intangible losses, arising out of or in connection with the use or inability to use our service.
  By using our service, you acknowledge and agree that the generated content may not be error-free and that you use it at your own risk.
  We reserve the right to modify or discontinue any aspect of the service at any time without notice. Users are responsible for
  regularly reviewing these terms for any changes. Continued use of the service after any such changes shall constitute your consent
  to such changes.
</p>

<h2 className="text-2xl font-bold ml-3">Intellectual Property Rights</h2>
<p className="text-lg ml-3">The content provided through our service, including but not limited to text, graphics, logos, images, and software, is the property of our company and is protected by intellectual property laws, including copyright and trademark laws. You agree not to reproduce, modify, distribute, or publicly display any of the content provided by our service without our prior written consent.</p>

<h2 className="text-2xl font-bold ml-3">Governing Law</h2>
<p className="text-lg ml-3">These terms and conditions shall be governed by and construed in accordance with the laws of USA, without regard to its conflict of law provisions. Any dispute arising out of or relating to these terms and conditions shall be exclusively resolved by the competent courts of Des Moines.</p>

<h2 className="text-2xl font-bold ml-3">Indemnification</h2>
<p className="text-lg ml-3">You agree to indemnify and hold harmless our company and its affiliates, officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, or expenses (including attorneys' fees) arising out of or relating to your use of our service or violation of these terms and conditions.</p>

<h2 className="text-2xl font-bold ml-3">Termination</h2>
<p className="text-lg ml-3">We reserve the right to terminate or suspend your access to our service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the terms.</p>

<h2 className="text-2xl font-bold ml-3">Changes to Terms</h2>
<p className="text-lg ml-3">We reserve the right, at our sole discretion, to modify or replace these terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect.</p>



  </div>;
};

export default page;

