import React from "react";

const page = () => {
  return <div>
    <h1>Terms of Service</h1>
    <p>By using our resume builder service, you agree to the following terms and conditions:<br></br>
      The content generated by our service, including but not limited to resumes, cover letters, and any other related materials
      may be generated or modified using artificial intelligence algorithms. While we strive for accuracy and quality, we cannot guarantee
      the completeness, accuracy, reliability, suitability, or availability of the generated content. Users are solely responsible
      for reviewing and verifying the accuracy and appropriateness of the generated content before use. We shall not be liable for any
      direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of profits,
      goodwill, use, data, or other intangible losses, arising out of or in connection with the use or inability to use our service.
      By using our service, you acknowledge and agree that the generated content may not be error-free and that you use it at your own risk.
      We reserve the right to modify or discontinue any aspect of the service at any time without notice. Users are responsible for
      regularly reviewing these terms for any changes. Continued use of the service after any such changes shall constitute your consent
      to such changes.
</p>
  </div>;
};

export default page;

